Hi All, 

The {% if client.name != client.subName %} {{client.name}} {{client.subName}} {% endif %}
{% if client.name == client.subName %} {{client.name}} {% endif %}visit has been closed successfully.
<br/>				
<p>To view the visit collaterals, please <a href="{{loginPath}}/{{createBy.id}}/{{createBy.local.password}}/visitClosure/{{visitId}}" title="CSC Visit Portal">click here </a>.</p>
<p>
Thanks.<br>
CSC India Visit Management Team<br>
Connect with us at: Link to C3 page
</p>
<hr/>