Dear Visit Participant,

Your are part of the following customer visit...

Title: {{title}}
Client: {{client.name}}
Start Date: {{startDate|date('jS \o\f F, Y')}}
End Date: {{endDate|date('jS \o\f F, Y')}}
Locations: {{locations}}

Please login the visit portal for more info on the visit agenda, schedules and your participation details

Best Regards,
Visit Portal Team

Note: This is an auto generated mail from Visit Portal. Please do not reply.
