Dear Visit Manager,

New Visit Agenda submitted by {{submittedBy}} on {{submittedOn}}.

Agenda Summary:

Client: {{client}}
Start Date: {{startDate}}
End Date: {{endDate}}
Locations: {{locations}}

Please click here {{link}} (or copy paste the below link in your browser address bar) to open the visit agenda. You can pick it by clicking on assign to myself link on the page.

{{link}}

Best Regards,
Visit Portal Team

Note: This is an auto generated mail from Visit Portal. Please do not reply.
